[theme]

[theme.options]
is_display = true
display_time = "waveshare144lcd"
resolution = [128, 128]
hi-res = true
bg = true
bg_image = "128x128-b.png"
#Bold, BoldSmall, Medium, Huge, BoldBig, Small
font_sizes = [10, 8, 10, 18, 25, 9]
label_spacing = 9
fps = 10
font = 'DejaVuSansMono'
status_font = 'DejaVuSansMono'

[theme.main_elements]

[theme.main_elements.face]
position = [0, 43]
font = "Huge"
color = "magenta"

[theme.main_elements.name]
position = [0,14]
font = "Bold"
color = "lime"

# Exemple test to add icons to an element label/value
#[theme.main_elements.test_icon]
#position = [0, 18]
#label_icon = true
#label = ["/.../.../.../icon.png"]
#value_icon = true
#value = ["/.../.../.../icon2.png", "/.../.../.../icon3.png"]
#label_font = "Bold"
#text_font = "Medium"
#color = "BLACK"

[theme.main_elements.channel]
position = [0, 0]
label = "CH"
value = "00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.aps]
position = [0, 71]
label = "APS"
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.uptime]
position = [0, 25]
label = "UP"
value = "00:00:00"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.line1]
position = [0, 12, 127, 12]
color = "lime"

[theme.main_elements.line2]
position = [0, 116, 127, 116]
color = "lime"

[theme.main_elements.friend_face]
position = [12, 88]
font = "Bold"
color = "lime"

[theme.main_elements.friend_name]
position = [1, 103]
font = "BoldSmall"
color = "lime"

[theme.main_elements.shakes]
position = [26, 117]
label = "PWND "
value = "0 (00)"
label_font = "Bold"
text_font = "Medium"
color = "lime"

[theme.main_elements.mode]
position = [0, 117]
value = "AUTO"
font = "Bold"
color = "lime"

[theme.main_elements.status]
position = [65, 26]
value = "AUTO"
font = "Bold"
color = "lime"
wrap = true
max = 20

[theme.plugin_elements]

[theme.plugin_elements.crack_house]

[theme.plugin_elements.crack_house.crack_house]
position = [-10, 185]
label_font = "Bold"
text_font = "Small"
color = "BLACK"

[theme.plugin_elements.crack_house.crack_house_stats]
position = [-10, 170]
label_font = "Bold"
text_font = "Small"
color = "BLACK"
